Mobile version
MICHAELKITH/mobile-version-portfolio pull request #1
Opened 2023-01-11 14:54 UTC by MICHAELKITH

### **In this milestone:**
**I have commited;**
1. index.html file
2. style.css file
3. images files

2023-01-11 16:32 UTC, Ugboaja-Uchechi requested changes
Hi @MICHAELKITH , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 16:32 UTC, Ugboaja-Uchechi commented on style.css
> +}
- [ ] Great job 👍. Kindly make sure your `About Myself` text size looks as close as possible to your chosen Figma design 🙏 
- [ ] Kindly make sure you give your text the correct color `#172B4D`

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/211859549-c2ec5c72-43c9-47eb-ae5a-91ca8df509a1.png)  |  ![image](https://user-images.githubusercontent.com/74814780/211859828-2ad28fc9-6da6-4b8a-8247-02acfb6c8eb0.png)

2023-01-11 16:32 UTC, Ugboaja-Uchechi commented on style.css
> +  gap: 10px;
- [ ] Kindly give your `button` more margin as seen in your chosen Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/211861197-0ee6e595-0d36-4fb0-b76c-4c5a84906afc.png)  |  ![image](https://user-images.githubusercontent.com/74814780/211861048-46110787-995c-4f05-a02a-14c2721e8130.png)

2023-01-11 16:32 UTC, Ugboaja-Uchechi commented on style.css
> +  background-color: var(--container-bg);
- [ ] Kindly remove the `border` around your design as it isn't in your chosen Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/211861834-b87f8f5f-1c3d-4316-a17e-f32d5fa642bc.png)  |  ![image](https://user-images.githubusercontent.com/74814780/211861758-3fcc72f8-b262-46f8-8551-392c0e03d8c8.png)

2023-01-11 16:32 UTC, Ugboaja-Uchechi commented on style.css
> +  background-color: var(--button-color);
- [ ] Kindly give all your `buttons` interaction as seen in your chosen Figma design 🙏 

![image](https://user-images.githubusercontent.com/74814780/211862322-c73638cc-8932-4aee-bb43-339d40f9a7ea.png)

2023-01-12 08:14 UTC, levy002 approved these changes
## Hello @MICHAELKITH 
### I'm Levy, your PR reviewer

 Excellent, you nailed it :sunglasses: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights
- Good UI :heavy_check_mark: 
- All linters are passing :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 08:30 UTC, MICHAELKITH commented
@levy002 Good Job!

2023-01-12 08:30 UTC, merged